### ISSUE TITLE
Update Docs

### ISSUE THREAD

**Issue by MohammedBashiru** [bradymholt/vuejs-test-mocha-typescript-example#3]
Hello, Thanks for this awesome repo.

Since most people coming here might be beginners like me.
I think it would be helpful to give step by step process as in which dependencies to install.

I know looking at the **package.json** will let me know which packages to install, I still think adding them to the docs will be helpful.

**Comment by bradymholt** [comment]
Hello 👋 .  Simply running `npm install` should install them all.  I updated to add that here: https://github.com/bradymholt/vuejs-test-mocha-typescript-example/commit/c400ba7c47f387e66e5ad1ea1eb87e4ca6ae3685.
